# Build stage
FROM golang:1.19 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o /pong

# Run tests
FROM build-stage AS run-test-stage
RUN go test -v ./...

# Final stage
FROM alpine:latest

WORKDIR /

# Copy the binary from the build stage
COPY --from=build-stage /pong /pong

# Expose the desired port
EXPOSE 443
EXPOSE 80

# Define the environment variables
ENV PRODUCTION=true

# Run the application
ENTRYPOINT ["/pong"]
